### ISSUE TITLE
[BUG] Can't load replica panel

### ISSUE THREAD

**Issue by valentintraen** [charles-001/dolphie#26]
Hi !

Thanks for the correction of replica panel on source of RS. I have another problem with another ReplicaSet which works a lot more : 

![screen_4](https://github.com/charles-001/dolphie/assets/8438614/555b27b3-2cbf-435e-b137-356e729436cf)

Edit : It doesn't seem related, the panel doesn't load either with this load

![screen_6](https://github.com/charles-001/dolphie/assets/8438614/95d0cf20-19ba-4341-bd79-8aeac5ba3ef4)

 Replica panel never loads

![screen_5](https://github.com/charles-001/dolphie/assets/8438614/f2e304f8-43fa-4401-b1e0-7c9de987205c)

I don't see any queries coming from Dolphie on my instance. Are there any logs somewhere ?

I'm connecting on a remote Percona Server 8.0.29 instance from my computer.

Do not hesitate to ask me for more information

**Comment by charles-001** [comment]
Hi @valentintraen - when you open the replica panel, it connects to each replica using the credentials you provided to connect to the current host. If it's stuck on Loading, that tells me it's having an unknown issue connecting to it. Is this an asynchronous replica? 

As for queries not showing, that seems like a weird issue. You could try pressing `P` command to use processlist instead of performance_schema and see if that fixes the issue for you. Maybe you have certain performance_schema variables turned off? Hard to say for sure.

**Comment by valentintraen** [comment]
_when you open the replica panel, it connects to each replica using the credentials you provided to connect to the current host. If it's stuck on Loading, that tells me it's having an unknown issue connecting to it. Is this an asynchronous replica?_

Yes it's an asynchronous replica. I'm connecting with root account (to be sure).

 _As for queries not showing, that seems like a weird issue. You could try pressing P command to use processlist instead of performance_schema and see if that fixes the issue for you. Maybe you have certain performance_schema variables turned off? Hard to say for sure._


I misspoke. Everything works fine in Dolphie at the query level. When the replica panel loads, I connect live to my Percona Server instance to see if I see any requests coming from the session I opened with Dolphie, but I don't see anything.

**Comment by valentintraen** [comment]
Oh I found the solution ! Sorry, it's a compatibility issue between Dolphie and ProxySQL. If I don't go through proxySQL, everything works.

**Comment by valentintraen** [comment]
ProxySQL compatibility issue
