### ISSUE TITLE
query body looks like 䕓䕌呃⨠䘠佒⁍瑠汢灟祡敭瑮江獩恴怠恴

### ISSUE THREAD

**Issue by egorzagorskii** [charles-001/dolphie#42]
<img width="210" alt="image" src="https://github.com/charles-001/dolphie/assets/101588336/70c5c67a-0c88-48ac-9c6d-fc3f3035f6ad">

Hello. Trying dolphie for the first time. Some query in dolphie looks like in pictures, but there are no hieroglyphs in queries. System locale is en_US.UTF-8.

**Comment by egorzagorskii** [comment]
<img width="1152" alt="image" src="https://github.com/charles-001/dolphie/assets/101588336/9f9a5efd-9e86-48f7-b8de-eaf70c013f08">

**Comment by charles-001** [comment]
Hi @egorzagorskii - thanks for your bug report! This seems to be due to how I detect the encoding for BLOB/TEXT columns for decode. I just removed it to see if it's still _actually_ needed. Can you git clone the `main` branch of this repo, run `poetry install`, then `poetry run dolphie` with your normal parameters and see if your issue still exists?

**Comment by egorzagorskii** [comment]
Thank you for reply and very useful product. Looks like it helped, i can't see any hieroglyphs now. Tell me pls, is there a way to do force-refresh (like hitting "space" in innotop)? 1sec interval is okay but sometimes it is necessary to refresh processlist more frequently

**Comment by charles-001** [comment]
Hi @egorzagorskii - just added it. Do a `git pull` and give it a try.

**Comment by egorzagorskii** [comment]
Oh, great, it works :) thanks a lot
