### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by ppfloydde** [charles-001/dolphie#55]
As I try to connect to a 11.2.2-MariaDB I get the following Traceback:

`IndexError: tuple index out of range`

[dolphie_traceback.txt](https://github.com/charles-001/dolphie/files/14506732/dolphie_traceback.txt)

Connecting with normal MySQL/MariaDB Client is working. Connecting to other MariaDB and MySQL Server is working also.

**Comment by charles-001** [comment]
Hi @ppfloydde - thanks for sharing the traceback. It seems the issue stems from `pymsql`  when it tries to run `self._request_authentication` which returns `received unknown auth switch request`. I'm not sure what exactly with `pymysql` is the issue here unless it doesn't currently support MariaDB 11.2.2.

**Comment by charles-001** [comment]
Also, I am not supporting MariaDB at this time so any issues you find with using it will be on your own time to fix if you'd like to submit a PR :)
