### ISSUE TITLE
gracefully handle missing `performance_schema`

### ISSUE THREAD

**Issue by jycor** [charles-001/dolphie#78]
I believe that these lines
```python
        dolphie.main_db_connection.execute(MySQLQueries.ps_disk_io)
        dolphie.disk_io_metrics = dolphie.main_db_connection.fetchone()
```
from [here](https://github.com/charles-001/dolphie/blob/main/dolphie/app.py#L559-L560) need to be guarded by `dolphie.performance_schema_enabled` and `dolphie.use_performance_schema` as it's possible for the `performance_schema`database to not exists or `performance_schema = 'OFF'`, and `MySQLQueries.ps_disk_io` selects from `performance_schema` tables,

**Comment by charles-001** [comment]
@jycor - you're right, I will fix that. Is this causing an issue for you?

**Comment by jycor** [comment]
Yes, I have a workaround for now by just manually creating a `performance_schema` database and empty `file_summary_by_event_name` table.

Also, I believe that 
```
    if dolphie.use_performance_schema:
        processlist_query = MySQLQueries.ps_query
```

from [here](https://github.com/charles-001/dolphie/blob/main/dolphie/Panels/processlist_panel.py#L183-L184) should also be guarded by `dolphie.performance_schema_enabled` in addition to `dolphie.use_performance_schema`? as `ps_query` selects from `performance_schema.threads`.

However, I'm not sure why `reset_runtime_variables` sets `use_performance_schema` to `True` by default. [source](https://github.com/charles-001/dolphie/blob/main/dolphie/Dolphie.py#L157)
Perhaps I'm missing something?

I believe a similar workaround will work for the threads table too

**Comment by charles-001** [comment]
Gotcha. I've already fixed all the queries that require P_S along with this [code](https://github.com/charles-001/dolphie/blob/main/dolphie/Panels/processlist_panel.py#L183-L184) being protected by `performance_schema_enabled`. 

As for `use_performance_schema`, it's only for the processlist which I just noticed is poorly named. I've renamed the variable to `use_performance_schema_for_processlist` now. It's set to true by default because this [code](https://github.com/charles-001/dolphie/blob/353e65cc051d2b3ccb0ac8474b8abf3e9de33601/dolphie/Panels/processlist_panel.py#L15) alerts and sets it off for you.

**Comment by charles-001** [comment]
You don't need to create anymore workarounds, I'll have all these issues fixed here soon :)

**Comment by charles-001** [comment]
This is fixed in version `6.6.0`

**Comment by charles-001** [comment]
Hi @jycor - just checking in to make sure you can now run Dolphie well without PS turned on. How's it going?

**Comment by jycor** [comment]
Hey @charles-001, sorry the late reply. Yes, the latest version of dolphie is working for me now!
Thank you for all the assistance.
