### ISSUE TITLE
Unable to Kill if the Processlist Do Not Show Idle Threads

### ISSUE THREAD

**Issue by kolinkorr839** [charles-001/dolphie#86]
I like to use Dolphie to kill connections but typically I do not let it show idle threads (the key is `i` to toggle it on/off). But then if I don't show idle threads, I am not able to kill the connections. I tested this on version 6.7.0.

Here is how to reproduce this issue:

1. On terminal 1, create a session. This is connection 61457.

![Screenshot 2024-12-11 at 9 45 18 AM](https://github.com/user-attachments/assets/4ba34acc-d330-4ba4-8dd6-4b1a917e1563)

2. On terminal 2, drop the table and this will wait for the connection 61457 on terminal 1. This is connection 61476.

![Screenshot 2024-12-11 at 9 45 29 AM](https://github.com/user-attachments/assets/9db9b00a-3c14-47d3-91c4-0781dc7024f8)

3. In the `show processlist`, you can both connections.

![Screenshot 2024-12-11 at 9 45 44 AM](https://github.com/user-attachments/assets/887bdeb1-05ef-4a31-aa7f-62b96372592c)

4. Now if we try to kill it via Dolphie with idle threads not showing, it will say it cannot find it.

![Screenshot 2024-12-11 at 9 45 51 AM](https://github.com/user-attachments/assets/2f008388-9718-4119-9cb9-327dd3d01ad0)

5. And if I enable to show idle threads, I am able to kill connection 61457.

**Comment by charles-001** [comment]
Hi @kolinkorr839 – thank you for reaching out! The `k` command, as you may have assumed, checks the processlist to verify if the Thread ID exists. When you enable display of idle threads (`i` command), the Thread ID will appear as you begin typing, allowing you to select and kill it.

What I can do here is skip the processlist check altogether. Downside is you'll have to manually provide the Thread ID instead of it helping you with a popup list. I'm planning to push `7.0.1` here shortly with a few things I found and will include this.

**Comment by kolinkorr839** [comment]
For my specific use case, I have another terminal that is opened and it is running an SQL that shows the thread IDs of transactions that are causing metadata locks to a schema change that I am running. And it is super easy to just use "k" in Dolphie to kill those processlist IDs instead of typing the equivalent kill command in Aurora-MySQL.

**Comment by charles-001** [comment]
Just released `6.7.1` - give that a try and let me know if works as expected

**Comment by kolinkorr839** [comment]
I just tested it. It works great! Thank you.

**Comment by charles-001** [comment]
Awesome! Enjoy :)
